#!/bin/bash
set -euo pipefail

echo "=== Coolify Installation (Distrobox Edition) ==="
echo ""
echo "This image uses Distrobox for Coolify installation."
echo "Please use one of the following methods:"
echo ""
echo "Method 1: Automated installation from host"
echo "  From your host machine, run:"
echo "    just install-coolify"
echo ""
echo "Method 2: Manual installation inside container"
echo "  1. Enter the Coolify distrobox container:"
echo "     distrobox enter coolify"
echo "  2. Inside container, run:"
echo "     install-coolify-container"
echo "  3. Exit container (Ctrl+D)"
echo ""
echo "Method 3: Direct container command (from host)"
echo "  distrobox run coolify install-coolify-container"
echo ""
echo "After installation, Coolify will auto-start on subsequent boots."
echo "Access Coolify at: http://localhost:8000"
echo ""
echo "For more details, see README.md"
exit 0